service:
  name: portfolio-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  stage: prod
  runtime: nodejs8.10
  region: ap-northeast-1
  logRetentionInDays: 3

functions:
  portfolio02-qiita:
    handler: qiita.hello
    layers:
      - arn:aws:lambda:ap-northeast-1:768243342063:layer:portfolioLayer:8
    events:
      - schedule: cron(0 * * * ? *)
    environment:
      collection: qiita_articles
      endpoint: https://qiita.com/api/v2/users/kousaku-maron/items

  portfolio02-github:
    handler: github.hello
    layers:
      - arn:aws:lambda:ap-northeast-1:768243342063:layer:portfolioLayer:8
    events:
      - schedule: cron(0 * * * ? *)
    environment:
      collection: github_repositories
      endpoint: https://api.github.com/users/kousaku-maron/repos

custom:
  prune:
    automatic: true
    number: 3